routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EstudiantesController;
use App\Http\Controllers\ProgramasController;
use App\Http\Controllers\AreasController;
use App\Http\Controllers\CertificadosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\UbicacionesController;
use App\Http\Controllers\GeneradorController;
use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\AulasController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    
    Route::get('/', function () {
        return view('home');
    });

    Route::resource('estudiantes', EstudiantesController::class);    
    Route::group(['prefix' => 'gestion-estudiante'], function () {   
        Route::get('get_sugerencia',  [EstudiantesController::class ,'get_sugerencia'])->name('estudiantes.get-sugerencia');
       
    });
    Route::resource('programas', ProgramasController::class);
    Route::resource('areas', AreasController::class);

    Route::group(['prefix' => 'ubicaciones'], function () {   
        Route::get('get_ciudades',  [UbicacionesController::class ,'get_ciudades'])->name('ubicaciones.get-ciudades');
       
    });
    
    Route::resource('sedes', UbicacionesController::class);
    Route::group(['prefix' => 'gestion-sedes'], function () {   
        Route::get('get_sugerencia',  [UbicacionesController::class ,'get_sugerencia'])->name('sedes.get-sugerencia');
       
    });
    
    Route::resource('cursos', CursosController::class);
    Route::group(['prefix' => 'gestion-cursos'], function () {   
        Route::get('edit_estudiantes/{curso}',  [CursosController::class ,'edit_estudiantes'])->name('cursos.get-estudiantes');
        Route::post('agregar_estidiantes',  [CursosController::class ,'agregar_estidiantes'])->name('cursos.add-estudiantes');
        Route::post('aprobar_estidiantes',  [CursosController::class ,'aprobar_estidiantes'])->name('cursos.aprobar-estudiantes');
        Route::get('get_sugerencia',  [CursosController::class ,'get_sugerencia'])->name('cursos.get-sugerencia');
       
    });

    Route::resource('aulas', AulasController::class);

    Route::get('empleados/profile',  [EmpleadosController::class ,'profile'])->name('empleados.profile');

    Route::resource('empleados', EmpleadosController::class);
    Route::resource('certificados', CertificadosController::class);
   // Auth::routes(["register" => false]);
});
Route::group(['prefix' => 'certificados-digitales'], function () {   
    Route::get('get_certificado_curso',  [GeneradorController::class ,'get_certificado_curso']);
    Route::get('',  [GeneradorController::class ,'index']);
    Route::get('get_lita_certificados',  [GeneradorController::class ,'get_lita_certificados']);   
   
});

/*
    //Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
 */

/*Route::get('/register',function(){
    return abort(404);
 })->name('register')->middleware('guest');*/

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/dashboard.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-xl sm:rounded-lg">
                <x-jet-welcome />
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/home.blade.php
@extends('adminlte::page')
@section('content_header')
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
        <!-- Small boxes (Stat box) -->
        <div class="row">
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <a href="{{route('sedes.index')}}" class="">
              <!-- small box -->
              <div class="small-box bg-info">
                  <div class="inner p-1">
                    <h3>Sedes</h3>
                    <p>lifecare</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-house-user"></i>
                  </div>
            <a href="#" class="small-box-footer">Mas Información <i class="fas fa-arrow-circle-right"></i></a>
            </div>
            </a>
        </div>
        <!-- ./col -->

          <div class="col-lg-3 col-6">
              <a href="{{route('estudiantes.index')}}" class="">
                <!-- small box -->
                <div class="small-box bg-success">
                    <div class="inner p-1">
                      <h3>Estudiantes</h3>
                      <p>lifecare</p>
                    </div>
                    <div class="icon">
                      <i class="fas fa-users"></i>
                    </div>
              <a href="#" class="small-box-footer">Mas Información <i class="fas fa-arrow-circle-right"></i></a>
              </div>
              </a>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
              <a href="{{route('programas.index')}}" class="">
                <!-- small box -->
                <div class="small-box bg-info">
                    <div class="inner p-1">
                      <h3>Ofertas</h3>
                      <p>lifecare</p>
                    </div>
                    <div class="icon">
                      <i class="fas fa-book"></i>
                    </div>
              <a href="#" class="small-box-footer">Mas Información <i class="fas fa-arrow-circle-right"></i></a>
              </div>
              </a>
          </div>
          <!-- ./col -->
          <div class="col-lg-3 col-6">
            <a href="{{route('cursos.index')}}" class="">
              <!-- small box -->
              <div class="small-box bg-danger">
                  <div class="inner p-1">
                    <h3>Cursos y diplomados</h3>
                    <p>lifecare</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-book"></i>
                  </div>
                  <a href="#" class="small-box-footer">Mas Información <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </a>
          </div>


          <div class="col-lg-3 col-6">
            <a href="{{route('empleados.index')}}" class="">
              <!-- small box -->
              <div class="small-box bg-primary">
                  <div class="inner p-1">
                    <h3>Empleados</h3>
                    <p>lifecare</p>
                  </div>
                  <div class="icon">
                    <i class="fas fa-book"></i>
                  </div>
                  <a href="#" class="small-box-footer">Mas Información <i class="fas fa-arrow-circle-right"></i></a>
              </div>
            </a>
          </div>

        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
  </section>
  <!-- /.content -->
@stop

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>