routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EstudiantesController;
use App\Http\Controllers\ProgramasController;
use App\Http\Controllers\AreasController;
use App\Http\Controllers\CertificadosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\UbicacionesController;
use App\Http\Controllers\GeneradorController;
use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\AulasController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    
    Route::get('/', function () {
        return view('home');
    });

    Route::resource('estudiantes', EstudiantesController::class);    
    Route::group(['prefix' => 'gestion-estudiante'], function () {   
        Route::get('get_sugerencia',  [EstudiantesController::class ,'get_sugerencia'])->name('estudiantes.get-sugerencia');
       
    });
    Route::resource('programas', ProgramasController::class);
    Route::resource('areas', AreasController::class);

    Route::group(['prefix' => 'ubicaciones'], function () {   
        Route::get('get_ciudades',  [UbicacionesController::class ,'get_ciudades'])->name('ubicaciones.get-ciudades');
       
    });
    
    Route::resource('sedes', UbicacionesController::class);
    Route::group(['prefix' => 'gestion-sedes'], function () {   
        Route::get('get_sugerencia',  [UbicacionesController::class ,'get_sugerencia'])->name('sedes.get-sugerencia');
       
    });
    
    Route::resource('cursos', CursosController::class);
    Route::group(['prefix' => 'gestion-cursos'], function () {   
        Route::get('edit_estudiantes/{curso}',  [CursosController::class ,'edit_estudiantes'])->name('cursos.get-estudiantes');
        Route::post('agregar_estidiantes',  [CursosController::class ,'agregar_estidiantes'])->name('cursos.add-estudiantes');
        Route::post('aprobar_estidiantes',  [CursosController::class ,'aprobar_estidiantes'])->name('cursos.aprobar-estudiantes');
        Route::get('get_sugerencia',  [CursosController::class ,'get_sugerencia'])->name('cursos.get-sugerencia');
       
    });

    Route::resource('aulas', AulasController::class);

    Route::get('empleados/profile',  [EmpleadosController::class ,'profile'])->name('empleados.profile');

    Route::resource('empleados', EmpleadosController::class);
    Route::resource('certificados', CertificadosController::class);
   // Auth::routes(["register" => false]);
});
Route::group(['prefix' => 'certificados-digitales'], function () {   
    Route::get('get_certificado_curso',  [GeneradorController::class ,'get_certificado_curso']);
    Route::get('',  [GeneradorController::class ,'index']);
    Route::get('get_lita_certificados',  [GeneradorController::class ,'get_lita_certificados']);   
   
});

/*
    //Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
 */

/*Route::get('/register',function(){
    return abort(404);
 })->name('register')->middleware('guest');*/

app/Models/Ubicacione.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Ubicacione extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $fillable = [
        'nombre','direccion','rango_inicio','prefijo','ciudad_id'
    ];
}

app/Http/Controllers/UbicacionesController.php
<?php

namespace App\Http\Controllers;
use App\Models\Ubicacione;
use App\Http\Requests\UbicacionRequest;

use Mappweb\Mappweb\Helpers\Util;

use Illuminate\Http\Request;
use DB;


class UbicacionesController extends Controller
{
    public function index(){
        $busqueda = trim(request("buscar") ? request("buscar"): "");
        
        $query =  Ubicacione::select('ubicaciones.*','c.nombre as ciudad')
            ->join('ciudades as c', 'c.id', '=', 'ubicaciones.ciudad_id');
            
        if(!empty($busqueda)){
            $query->where(function($query) use ($busqueda)
            {		 	
                $query->where('ubicaciones.nombre', 'like', "%".$busqueda."%");  
                $query->orWhere('ubicaciones.direccion', 'like', "%".$busqueda."%");  
            });
        }
        $data['busqueda'] = $busqueda;
        $data['ubicaciones'] = $query->paginate()->appends(request()->query());
        return View("ubicaciones.index",$data);

    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['object'] = new Ubicacione;
        $data["ciudades"] =  DB::table("ciudades as c")
        ->select(["c.nombre", "c.id","dep.nombre as dep_nombre"])
        ->join("departamentos as dep", "dep.id","=","c.departamento_id")
        ->where("c.eliminado",0)->where("dep.eliminado",0)->where("c.pais_code","CO")->get();
        return view('ubicaciones.modal-registro', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UbicacionRequest $request)
    {
        
        $objets = Util::updateOrCreate(Ubicacione::class, $request);        
        $data['success'] = (boolean) $objets; 
        $data['reload_page'] = true;    
        Util::addToastToData($data);

        return response()->crud($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['object'] = Ubicacione::find($id);
        $data["ciudades"] =  DB::table("ciudades as c")
        ->select(["c.nombre", "c.id","dep.nombre as dep_nombre"])
        ->join("departamentos as dep", "dep.id","=","c.departamento_id")
        ->where("c.eliminado",0)->where("dep.eliminado",0)->where("c.pais_code","CO")->get();
        
        return view('ubicaciones.modal-registro', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UbicacionRequest $request, $id)
    {
        $objets = Util::updateOrCreate(Ubicacione::class, $request, $id);
        
        $data['success'] =(boolean) $objets;
        
        Util::addToastToData($data);
        $data['reload_page'] = true;    

        return response()->crud($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        

    }
  function get_ciudades()
  {
    $search = request("term");
    

    $data =  DB::table("ciudades as c")->select(["c.nombre as text", "c.id"])->
    where(function($query) use ($search)
    {		 	
        $query->where('c.nombre', 'like', "%".$search."%");
       // $query->orWhere('ct.name', 'ilike', "%$search%");        
    })
    ->where("c.eliminado",0)->limit(30)->get();

   return response()->json($data,200);

  }

    public function get_sugerencia()
    {
        $search = request("term");    
        $limit = 30;
        $data_sugerencia =  DB::table("ubicaciones as e")->select(["e.nombre as label","e.id as id"])->
        where(function($query) use ($search)
        {		 	
            $query->where('e.nombre', 'like', "%".$search."%");      
        })
        ->limit(30)->get()->toArray();
        

        $data =  DB::table("ubicaciones as e")->select(["e.prefijo as label","e.id as id"])->
        where(function($query) use ($search)
        {		 	
            $query->where('e.prefijo', 'like', "%".$search."%");  
        })
        ->limit(30)->get()->toArray();

        foreach ($data as $val) {
            $data_sugerencia[] = $val;
        }

        return response()->json($data_sugerencia,200);

    }
}

resources/views/ubicaciones/index.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="css/jquery-ui.min.css">
@endsection

@section('content_header')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="/">Inicio</a></li>
                    <li class="breadcrumb-item active">Sedes</li>
                </ol>

            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

@stop


@section('content')


<!-- /.card -->

<div class="card card-outline card-success">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">Gestión de sedes <span class="badge badge-success">
                {{  $ubicaciones->total()}}</span></h3>

        <div class="card-tools">
            <div class="btn-group">
                <a href="{{ route('sedes.create') }}" class="btn btn-success open-modal">
                    <i class="fas fa-plus"></i> Crear sede
                </a>
            </div>


        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <form action="{{ route('sedes.index') }}" method="get">
            <div class="row p-1">
                <duv class="col-md-3">
                    <div class="input-group input-group-sm">
                        <input id="buscador" name="buscar" type="text" value="{{$busqueda}}"
                            placeholder="Ingresa un palabra para Buscar" class="form-control">
                        <span class="input-group-append">
                            <button type="submit" id="btn-subtmit" class="btn btn-info btn-flat">Buscar</button>
                        </span>
                    </div>
                </duv>
                <duv class="col-md-3">
                    <button type="button" onclick="redireccionar()" id="btn-subtmit" class="btn btn-info btn-info btn-sm">Restablecer búsqueda</button>
                </duv>
        </form>
    </div>
    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th style="width: 10px">ID</th>
                <th>Nombre</th>
                <th>Prefijo</th>
                <th>Ciudad</th>
                <th>Dirección</th>
                <th>Fecha registro</th>
                <th style="width: 100px">Opc</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($ubicaciones as $ubicacion)
            <tr>
                <td> {{ $ubicacion->id }} </td>

                <td> {{ $ubicacion->nombre }} </td>
                <td> {{ $ubicacion->prefijo }} </td>
                <td> {{$ubicacion->ciudad}} </td>
                <td> {{$ubicacion->direccion}} </td>
                <td> {{  date('d-M-Y',strtotime($ubicacion->created_at)) }} </td>
                <td>
                    <a class="open-modal bg-info btn-sm"
                        href="{{route('sedes.edit',['sede' => $ubicacion->id])}}">
                        <i class="fas fa-pencil-alt"></i>
                    </a>
                </td>
            </tr>
            @endforeach

            @if ($ubicaciones->count()==0)
            <tr>
                <td colspan="5" class="text-center"> No hay sedes registradas</td>
            </tr>
            @endif

        </tbody>
    </table>
</div>
<div class="card-footer clearfix">
    {{ $ubicaciones->render("pagination::bootstrap-4") }}
</div>


<!-- /.card-body -->
</div>

<div id="modal-add"></div>


@stop
@section('js')
<script src="js/jquery-ui.min.js"></script>
<script>
$(document).ready(function() {
    $("#buscador").autocomplete({
        source: '<?php echo route("sedes.get-sugerencia"); ?>',
        delay: 300,
        autoFocus: false,
        minLength: 1,
        select: function(event, ui) {
            event.preventDefault();
            $("#buscador").val(ui.item.label);
            $("#btn-subtmit").click();

        }
    });

});
function redireccionar(){
    window.location='{{route("sedes.index")}}';
}
</script>
@endsection

resources/views/ubicaciones/modal-registro.blade.php
<link rel="stylesheet" href="css/select2.min.css">

<div class="modal fade" id="modal-lg" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h4 class="modal-title">Datos de la sede</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form id="formCursos" autocomplete="off" class="save-ajax" method="{{$object->exists? 'POST':'POST'}}"
                data-has-files='true'
                action="{{ $object->exists? route('sedes.update', ['sede' => $object->id]):route('sedes.store') }}">
                @csrf
                @if($object->exists)
                <input type="hidden" value="{{$object->exists ? $object->id: '0'}}" id="id" name="id">
                <input hidden name="_method" value="PUT">
                @endif
                <div class="modal-body">

                    <div class="card-body row">
                        
                        <div class="col-sm-12">
                            <div class="form-group">
                                <label for="nombre">Nombre: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control text-capitalize" id="nombre" name="nombre"
                                    placeholder="Ingrese nombre de la sede" value="{{ $object->nombre }}">
                                <div data-feedback="nombre" class="text-danger">
                                </div>

                            </div>
                        </div>


                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="ciudad_id">Ciudad: <span
                                        class="text-danger">*</span></label>

                                <select lass="form-control select2" style="width: 100%;" name="ciudad_id" id="ciudad_id" >
                                <option value="" >-- Seleccione --</option>    
                                <?php  foreach ($ciudades as $c): ?>
                                    <option value="<?=$c->id?>" <?= $object->ciudad_id  == $c->id ? "selected": ""?>>
                                        <?=$c->nombre. " - ".$c->dep_nombre?></option>
                                    <?php endforeach; ?>
                                </select>
                                
                                <div data-feedback="ciudad_id" class="text-danger">
                                </div>
                            </div>
                        </div>
                        

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="direccion">Dirección: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control text-uppercase" name="direccion" id="direccion"
                                    placeholder="Ingrese direccion" value="{{ $object->direccion }}">
                                <div data-feedback="direccion" class="text-danger">
                                </div>

                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="prefijo">Prefijo: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" name="prefijo" id="prefijo"
                                    placeholder="Ingrese prefijo identificador" value="{{ $object->prefijo }}">
                                <div data-feedback="prefijo" class="text-danger">
                                </div>

                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="rango_inicio">Rango de inicio: <span class="text-danger">*</span></label>
                                <input type="number" class="form-control text-capitalize" name="rango_inicio" id="rango_inicio"
                                    placeholder="Ingrese rango de inicio consecutivo" value="{{ $object->rango_inicio }}">
                                <div data-feedback="rango_inicio" class="text-danger">
                                </div>

                            </div>
                        </div>


                    </div>
                    <!-- /.card-body -->

                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn-submit btn btn-primary">Guardar</button>
                </div>
            </form>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<script src="js/select2.full.min.js"></script>
<script>
jQuery(document).ready(function() {

    $("#ciudad_id").select2({
        placeholder: "Seleccione una Ciudad",
        theme: 'bootstrap4',
        
    });

});
</script>