routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EstudiantesController;
use App\Http\Controllers\ProgramasController;
use App\Http\Controllers\AreasController;
use App\Http\Controllers\CertificadosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\UbicacionesController;
use App\Http\Controllers\GeneradorController;
use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\AulasController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    
    Route::get('/', function () {
        return view('home');
    });

    Route::resource('estudiantes', EstudiantesController::class);    
    Route::group(['prefix' => 'gestion-estudiante'], function () {   
        Route::get('get_sugerencia',  [EstudiantesController::class ,'get_sugerencia'])->name('estudiantes.get-sugerencia');
       
    });
    Route::resource('programas', ProgramasController::class);
    Route::resource('areas', AreasController::class);

    Route::group(['prefix' => 'ubicaciones'], function () {   
        Route::get('get_ciudades',  [UbicacionesController::class ,'get_ciudades'])->name('ubicaciones.get-ciudades');
       
    });
    
    Route::resource('sedes', UbicacionesController::class);
    Route::group(['prefix' => 'gestion-sedes'], function () {   
        Route::get('get_sugerencia',  [UbicacionesController::class ,'get_sugerencia'])->name('sedes.get-sugerencia');
       
    });
    
    Route::resource('cursos', CursosController::class);
    Route::group(['prefix' => 'gestion-cursos'], function () {   
        Route::get('edit_estudiantes/{curso}',  [CursosController::class ,'edit_estudiantes'])->name('cursos.get-estudiantes');
        Route::post('agregar_estidiantes',  [CursosController::class ,'agregar_estidiantes'])->name('cursos.add-estudiantes');
        Route::post('aprobar_estidiantes',  [CursosController::class ,'aprobar_estidiantes'])->name('cursos.aprobar-estudiantes');
        Route::get('get_sugerencia',  [CursosController::class ,'get_sugerencia'])->name('cursos.get-sugerencia');
       
    });

    Route::resource('aulas', AulasController::class);

    Route::get('empleados/profile',  [EmpleadosController::class ,'profile'])->name('empleados.profile');

    Route::resource('empleados', EmpleadosController::class);
    Route::resource('certificados', CertificadosController::class);
   // Auth::routes(["register" => false]);
});
Route::group(['prefix' => 'certificados-digitales'], function () {   
    Route::get('get_certificado_curso',  [GeneradorController::class ,'get_certificado_curso']);
    Route::get('',  [GeneradorController::class ,'index']);
    Route::get('get_lita_certificados',  [GeneradorController::class ,'get_lita_certificados']);   
   
});

/*
    //Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
 */

/*Route::get('/register',function(){
    return abort(404);
 })->name('register')->middleware('guest');*/

app/Models/Estudiante.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Estudiante extends Model
{    
    use SoftDeletes;
    protected $table  = 'estudiantes';
    
    protected $fillable = [
        "tipo_documento",
        "documento_n",
        "nombre",
        "segundo_nombre" ,
        "apellido" ,
        "apellido2",
        "pais_code" ,
        "departamento_id" ,
        "ciudad_id" ,
        "fecha_expedicion",
        "expedicion_ciudad_id",
        "direccion" ,
        "celular",
        "email"
    ];

    public static function existe_decuemunto($id, $tipo, $numero)
    {
        $query = Estudiante::where("tipo_documento",$tipo)->where("documento_n",trim($numero));
        if($id > 0)
            $query->where("id","!=", $id);
        
        return $query->exists();
    }
}

app/Http/Controllers/EstudiantesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Estudiante;
use App\Models\User;
use App\Http\Requests\EstudianteRequest;
use DB;
use Mappweb\Mappweb\Helpers\Util;


class EstudiantesController extends Controller
{

    

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $busqueda = trim(request("buscar") ? request("buscar"): "");
        
        $query =  Estudiante::select('estudiantes.*',DB::raw('CAST(estudiantes.codigo AS CHAR) AS codigo'),);
        if(!empty($busqueda)){
            $query->where(function($query) use ($busqueda)
            {		 	
                $query->where('documento_n', 'like', "%".$busqueda."%");  
                $query->orWhere('email', 'like', "%".$busqueda."%");  
                $query->orWhere(DB::raw("CONCAT(nombre, ' ', segundo_nombre, ' ', apellido, ' ', apellido2)"), 'LIKE', "%".$busqueda."%");  
            });
        }
        $data['busqueda'] = $busqueda;
        $data['estudiantes'] = $query->paginate()->appends(request()->query());
        return View("estudiantes.index",$data);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['object'] = new Estudiante;
        $data["tipos_doc"] = User::get_document_type();       
        $data["ciudades"] =  DB::table("ciudades as c")
        ->select(["c.nombre", "c.id","dep.nombre as dep_nombre"])
        ->join("departamentos as dep", "dep.id","=","c.departamento_id")
        ->where("c.eliminado",0)->where("dep.eliminado",0)->where("c.pais_code","CO")->get();
        return view('estudiantes.modal-registro', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EstudianteRequest $request)
    {
        try {
            DB::beginTransaction();

            if(Estudiante::existe_decuemunto(null, request("tipo_documento"), request("documento_n"))){           
                return response()->json(["message"=>"Estudiante registrado.",
                "errors" =>["documento_n"=>["Tipo Documento y número ya existe"],
                ]], 422);
                
            }
            $objets = Util::updateOrCreate(Estudiante::class, $request); 
            
            $objets->codigo = $objets->id;

            if($objets->save()){
                DB::commit();
                $data['success'] = true;

            }else{
                DB::rollBack();
                $data['success'] = false;
            }
             
            $data['reload_page'] = true;    
            Util::addToastToData($data);
    
            return response()->crud($data);

        } catch (\Throwable $th) {
            DB::rollBack();
            $data['success'] = false; 
            $data['msg_error'] =$th;
            Util::addToastToData($data);
            return response()->crud($data);
        }

        



        
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        echo"ok";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($estudiante)
    {
        $data['object'] = Estudiante::find($estudiante);      
        $data["tipos_doc"] = User::get_document_type();
        $data["ciudades"] =  DB::table("ciudades as c")
        ->select(["c.nombre", "c.id","dep.nombre as dep_nombre"])
        ->join("departamentos as dep", "dep.id","=","c.departamento_id")
        ->where("c.eliminado",0)->where("dep.eliminado",0)->where("c.pais_code","CO")->get();

        return view('estudiantes.modal-registro', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EstudianteRequest $request, $id)
    {
        if(Estudiante::existe_decuemunto($id, request("tipo_documento"), request("documento_n"))){           
            return response()->json(["message"=>"Estudiante registrado.",
            "errors" =>["documento_n"=>["Tipo Documento y número ya existe"],
            ]], 422);
           
        }
        $objets = Util::updateOrCreate(Estudiante::class, $request, $id);      
        $data['success'] = (boolean) $objets;
        $data['reload_page'] = true;        
        Util::addToastToData($data);

        return response()->crud($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data['success'] = false;

        $estudiante = Estudiante::find($id);
        $data['success'] = $estudiante->delete();
        
        return response()->crud($data);

    }

    public function get_sugerencia()
    {
        $search = request("term");    
        $limit = 30;
        $data_sugerencia =  DB::table("estudiantes as e")->select(["e.documento_n as label","e.id as id"])->
        where(function($query) use ($search)
        {		 	
            $query->where('e.documento_n', 'like', "%".$search."%");      
        })
        ->whereNull('deleted_at')
        ->limit(30)->get()->toArray();
        

        $data =  DB::table("estudiantes as e")->select(["e.email as label","e.id as id"])->
        where(function($query) use ($search)
        {		 	
            $query->where('e.email', 'like', "%".$search."%");  
        })
        ->whereNull('deleted_at')
        ->limit(30)->get()->toArray();

        foreach ($data as $val) {
            $data_sugerencia[] = $val;
        }

        $data =  DB::table("estudiantes as e")->select([ DB::raw("CONCAT(nombre, ' ', segundo_nombre, ' ', apellido, ' ', apellido) as label"),"e.id as id"])->
        where(function($query) use ($search)
        { 
            $query->Where(DB::raw("CONCAT(nombre, ' ', segundo_nombre, ' ', apellido, ' ', apellido2)"), 'LIKE', "%".$search."%");
        })
        ->whereNull('deleted_at')
        ->limit(30)->get()->toArray();

        foreach ($data as $val) {
            $data_sugerencia[] = $val;
        }

        sort($data_sugerencia);
		
		//only return $limit suggestions
		if(count($data_sugerencia) > $limit)
		{
			$data_sugerencia = array_slice($suggestions, 0,$limit);
		}
        return response()->json($data_sugerencia,200);

    }

    
}

resources/views/estudiantes/index.blade.php
@extends('adminlte::page')

@section('css')
<link rel="stylesheet" href="css/jquery-ui.min.css">
@endsection

@section('content_header')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="/">Inicio</a></li>
                    <li class="breadcrumb-item active">Estudiantes</li>
                </ol>

            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

@stop


@section('content')


<!-- /.card -->

<div class="card card-outline card-success">
    <div class="card-header">
        <h3 class="card-title font-weight-bold">Gestión de estudiantes <span class="badge badge-success">
                {{  $estudiantes->total()}}</span></h3>

        <div class="card-tools">
            <div class="btn-group">
                <a href="{{ route('estudiantes.create') }}" class="btn btn-success open-modal">
                    <i class="fas fa-plus"></i> Crear estudiante
                </a>
            </div>


        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body p-0">
        <form action="{{ route('estudiantes.index') }}" method="get">
            <div class="row p-1">
                <duv class="col-md-3">
                    <div class="input-group input-group-sm">
                        <input id="buscador" name="buscar" type="text" value="{{$busqueda}}"
                            placeholder="Ingresa un palabra para Buscar" class="form-control">
                        <span class="input-group-append">
                            <button type="submit" id="btn-subtmit" class="btn btn-info btn-flat">Buscar</button>
                        </span>
                    </div>
                </duv>
                <duv class="col-md-3">
                    <button type="button" onclick="redireccionar()" class="btn btn-info btn-info btn-sm">Restablecer búsqueda</button>
                </duv>
        </form>
    </div>
    <table class="table table-hover text-nowrap">
        <thead>
            <tr>
                <th style="width: 100px">ID</th>
                <th style="width: 15px">Tipo Doc.</th>
                <th>N° Documento</th>
                <th>Nombre</th>
                <th>Celular</th>
                <th>Correo</th>
                <th style="width: 200px">Fecha registro</th>
                <th style="width: 100px">Opc</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($estudiantes as $estudiante)
            <tr id="row_{{$estudiante->id}}">
                <td> {{ (string) $estudiante->codigo }} </td>

                <td> {{ $estudiante->tipo_documento }} </td>
                <td> {{ $estudiante->documento_n }} </td>
                <td> {{ $estudiante->nombre }} {{ $estudiante->segundo_nombre }} {{ $estudiante->apellido }}
                    {{ $estudiante->apellido2 }} </td>
                <td> {{$estudiante->celular}} </td>
                <td> {{$estudiante->email}} </td>
                <td> {{  date('d-M-Y',strtotime($estudiante->created_at)) }} </td>
                <td>
                    <a class="open-modal bg-info btn-sm"
                        href="{{route('estudiantes.edit',['estudiante' => $estudiante->id])}}">
                        <i class="fas fa-pencil-alt"></i>
                    </a>

                    <a class="bg-danger btn-sm ml-1" href="javascript:eliminar_registro('{{$estudiante->id}}')">
                        <i class="fas fa-trash-alt"></i>
                    </a>
                </td>
            </tr>
            @endforeach

            @if ($estudiantes->count()==0)
            <tr>
                <td colspan="8" class="text-center"> No hay estudiantes registrados</td>
            </tr>
            @endif

        </tbody>
    </table>
</div>
<div class="card-footer clearfix">
    {{ $estudiantes->render("pagination::bootstrap-4") }}
</div>


<!-- /.card-body -->
</div>

<div id="modal-add"></div>


@stop
@section('js')
<script src="js/jquery-ui.min.js"></script>
<script src="/plugins/sweetalert/sweetalert2.min.js"></script>

<script>
$(document).ready(function() {
    $("#buscador").autocomplete({
        source: '<?php echo route("estudiantes.get-sugerencia"); ?>',
        delay: 300,
        autoFocus: false,
        minLength: 1,
        select: function(event, ui) {
            event.preventDefault();
            $("#buscador").val(ui.item.label);
            $("#btn-subtmit").click();

        }
    });

});
function redireccionar(){
    window.location='{{route("estudiantes.index")}}';
}
</script>

<script>

    function eliminar_registro(id){

        data = {
            "id": id,
            "_token": "{{ csrf_token() }}",
        },
        swal({
        title: '',
        text: "Esta seguro de eliminar el estudiante seleccionado?",
        type: "warning",
        showCancelButton: true,
        closeOnConfirm: false,
        showLoaderOnConfirm: true
        }).then(function(result) {
            if(result.value){
                $.ajax(
                {
                    url:"estudiantes/"+id,
                    type: 'DELETE',
                    data:data,
                    success :function(reponse){
                        if(reponse.success){
                            toastr.success('Estudiante eliminado exitosamente');
                            $("#row_"+id).remove();

                        }else{
                            toastr.error('No fue posible eliminar el estudiante');
                        }
                    },
                    error: function (response) {
                        toastr.error('Error al procesar la solicitud')
                    }
                });
            }

        });
    }
    
</script>
@endsection

resources/views/estudiantes/modal-registro.blade.php
<link rel="stylesheet" href="css/select2.min.css">

<div class="modal fade" id="modal-lg" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-success">
                <h4 class="modal-title">Datos del estudiante</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form id="formCursos" autocomplete="off" class="save-ajax" method="{{$object->exists? 'POST':'POST'}}"
                data-has-files='true'
                action="{{ $object->exists? route('estudiantes.update', ['estudiante' => $object->id]):route('estudiantes.store') }}">
                @csrf
                @if($object->exists)
                <input type="hidden" value="{{$object->exists ? $object->id: '0'}}" id="id" name="id">
                <input hidden name="_method" value="PUT">
                @endif
                <div class="modal-body">

                    <div class="card-body row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="tipo_documento">Tipo documento: <span class="text-danger">*</span> </label>
                                <select name="tipo_documento" id="tipo_documento" class="form-control">
                                    <?php  foreach ($tipos_doc as $key => $tipo): ?>
                                    <option value="<?=$key?>" <?= $object->tipo_documento ==$key ? "selected": ""?>>
                                        <?=$tipo?></option>
                                    <?php endforeach; ?>
                                </select>
                                <div data-feedback="tipo_documento" class="text-danger">
                                </div>

                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="documento_n">N° Documento: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control" id="documento_n" name="documento_n"
                                    placeholder="Ingrese N° Documento" value="{{ $object->documento_n }}">
                                <div data-feedback="documento_n" class="text-danger">
                                </div>

                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="nombre">Primer Nombre: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control text-capitalize" id="nombre" name="nombre"
                                    placeholder="Ingrese primer nombre" value="{{ $object->nombre }}">
                                <div data-feedback="nombre" class="text-danger">
                                </div>

                            </div>
                        </div>


                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="segundo_nombre">Segundo Nombre: </label>
                                <input type="text" class="form-control text-capitalize" name="segundo_nombre" id="segundo_nombre"
                                    placeholder="Ingrese Segundo nombre" value="{{ $object->segundo_nombre }}">
                                <div data-feedback="segundo_nombre" class="text-danger">
                                </div>

                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="apellido">Primer Apellido: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control text-capitalize" name="apellido" id="apellido"
                                    placeholder="Ingrese primer Apellido" value="{{ $object->apellido }}">
                                <div data-feedback="apellido" class="text-danger">
                                </div>

                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="apellido2">Segundo Apellido: <span class="text-danger">*</span></label>
                                <input type="text" class="form-control text-capitalize" name="apellido2" id="apellido2"
                                    placeholder="Ingrese segunco Apellido" value="{{ $object->apellido2 }}">
                                <div data-feedback="apellido2" class="text-danger">
                                </div>

                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="fecha_expedicion">Fecha de expedición del documento: <span
                                        class="text-danger">*</span></label>
                                <input type="date" class="form-control" name="fecha_expedicion" id="fecha_expedicion"
                                    placeholder="Ingrese fecha" value="{{ $object->fecha_expedicion }}">
                                <div data-feedback="fecha_expedicion" class="text-danger">
                                </div>

                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="expedicion_ciudad_id">Lugar de expedición del documento: <span
                                        class="text-danger">*</span></label>

                                <select lass="form-control select2" style="width: 100%;" name="expedicion_ciudad_id" id="expedicion_ciudad_id" >
                                <option value="" >-- Seleccione --</option>    
                                <?php  foreach ($ciudades as $c): ?>
                                    <option value="<?=$c->id?>" <?= $object->expedicion_ciudad_id  == $c->id ? "selected": ""?>>
                                        <?=$c->nombre. " - ".$c->dep_nombre?></option>
                                    <?php endforeach; ?>
                                </select>
                                
                                <div data-feedback="expedicion_ciudad_id" class="text-danger">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="email">Email:<span class="text-danger">*</span> </label>
                                <input class="form-control" name="email" id="email" placeholder="Ingrese Email"
                                    value="{{ $object->email }}">
                                <div data-feedback="email" class="text-danger">
                                </div>
                            </div>
                        </div>

                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="celular">Celular: </label>
                                <input class="form-control" name="celular" id="celular" placeholder="Ingrese Celular"
                                    value="{{ $object->celular }}">
                                <div data-feedback="celular" class="text-danger">
                                </div>
                            </div>
                        </div>

                    </div>
                    <!-- /.card-body -->

                </div>
                <div class="modal-footer justify-content-between">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="submit" class="btn-submit btn btn-primary">Guardar</button>
                </div>
            </form>

        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<script src="js/select2.full.min.js"></script>
<script>
jQuery(document).ready(function() {

    $("#expedicion_ciudad_id").select2({
        placeholder: "Seleccione una Ciudad",
        theme: 'bootstrap4',
        /*
        id: function(suggestion) {
            return suggestion.id;
        },
        ajax: {
            url: "<?=route("ubicaciones.get-ciudades")?>",
            dataType: 'json',           
            results: function(data, page) {
                return {
                    results: data
                };
            }
        },
        formatSelection: function(suggestion) {
            return suggestion.text;
        },
        formatResult: function(suggestion) {
            return suggestion.text;
        }*/
    });

});
</script>