routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\EstudiantesController;
use App\Http\Controllers\ProgramasController;
use App\Http\Controllers\AreasController;
use App\Http\Controllers\CertificadosController;
use App\Http\Controllers\CursosController;
use App\Http\Controllers\UbicacionesController;
use App\Http\Controllers\GeneradorController;
use App\Http\Controllers\EmpleadosController;
use App\Http\Controllers\AulasController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    
    Route::get('/', function () {
        return view('home');
    });

    Route::resource('estudiantes', EstudiantesController::class);    
    Route::group(['prefix' => 'gestion-estudiante'], function () {   
        Route::get('get_sugerencia',  [EstudiantesController::class ,'get_sugerencia'])->name('estudiantes.get-sugerencia');
       
    });
    Route::resource('programas', ProgramasController::class);
    Route::resource('areas', AreasController::class);

    Route::group(['prefix' => 'ubicaciones'], function () {   
        Route::get('get_ciudades',  [UbicacionesController::class ,'get_ciudades'])->name('ubicaciones.get-ciudades');
       
    });
    
    Route::resource('sedes', UbicacionesController::class);
    Route::group(['prefix' => 'gestion-sedes'], function () {   
        Route::get('get_sugerencia',  [UbicacionesController::class ,'get_sugerencia'])->name('sedes.get-sugerencia');
       
    });
    
    Route::resource('cursos', CursosController::class);
    Route::group(['prefix' => 'gestion-cursos'], function () {   
        Route::get('edit_estudiantes/{curso}',  [CursosController::class ,'edit_estudiantes'])->name('cursos.get-estudiantes');
        Route::post('agregar_estidiantes',  [CursosController::class ,'agregar_estidiantes'])->name('cursos.add-estudiantes');
        Route::post('aprobar_estidiantes',  [CursosController::class ,'aprobar_estidiantes'])->name('cursos.aprobar-estudiantes');
        Route::get('get_sugerencia',  [CursosController::class ,'get_sugerencia'])->name('cursos.get-sugerencia');
       
    });

    Route::resource('aulas', AulasController::class);

    Route::get('empleados/profile',  [EmpleadosController::class ,'profile'])->name('empleados.profile');

    Route::resource('empleados', EmpleadosController::class);
    Route::resource('certificados', CertificadosController::class);
   // Auth::routes(["register" => false]);
});
Route::group(['prefix' => 'certificados-digitales'], function () {   
    Route::get('get_certificado_curso',  [GeneradorController::class ,'get_certificado_curso']);
    Route::get('',  [GeneradorController::class ,'index']);
    Route::get('get_lita_certificados',  [GeneradorController::class ,'get_lita_certificados']);   
   
});

/*
    //Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    //Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');
 */

/*Route::get('/register',function(){
    return abort(404);
 })->name('register')->middleware('guest');*/

app/Models/Programa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Programa extends Model
{
    use HasFactory;

    use SoftDeletes;

    protected $fillable = [
        'codigo','nombre','descripcion','area_id'
    ];
}

app/Http/Controllers/ProgramasController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\ProgramaRequest;


use App\Models\Programa;
use App\Models\Area;
use App\Models\Curso;
use DB;

use Mappweb\Mappweb\Helpers\Util;

use Illuminate\Http\Request;

class ProgramasController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $data['programas'] =  Programa::select('programas.*', 'areas.nombre as area')
            ->join('areas', 'areas.id', '=', 'programas.area_id')
            ->paginate("50");
        
        return view("programas.index",$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['object'] = new Programa;
        $data['areas'] = Area::all();
        return view('programas.modal-registro', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProgramaRequest $request)
    {
        $objets = Util::updateOrCreate(Programa::class, $request);
        
        $data['success'] =(boolean) $objets;
        $data['reload_page'] = true;
        
        Util::addToastToData($data);

        return response()->crud($data);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Programa  $programa
     * @return \Illuminate\Http\Response
     */
    public function show($programa)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Programa  $programa
     * @return \Illuminate\Http\Response
     */
    public function edit($programa)
    {
        $data['object'] = Programa::find($programa);
        $data['areas'] = Area::all();
        return view('programas.modal-registro', $data);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Programa  $programa
     * @return \Illuminate\Http\Response
     */
    public function update(ProgramaRequest $request,$id)
    {
        $objets = Util::updateOrCreate(Programa::class, $request, $id);
        
        $data['success'] =(boolean) $objets;

        Curso::where('programa_id', $id)
            ->update(['nombre_curso' => request('nombre')]);

        Util::addToastToData($data);

        return response()->crud($data);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Programa  $programa
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            DB::beginTransaction();
        
            
            Curso::where('programa_id', $id)->delete();

            $objets = Programa::find($id);

            $data['success'] = $objets->delete(); 
            DB::commit();
        
        } catch (\Throwable $th) {
            DB::rollBack();
            $data['success'] = false;
        }
        
        
        return response()->crud($data);
    }
}

resources/views/programas/index.blade.php
@extends('adminlte::page')

@section('title', 'Ofertas')



@section('content_header')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-left">
                    <li class="breadcrumb-item"><a href="/">Inicio</a></li>
                    <li class="breadcrumb-item active">Ofertas</li>
                </ol>

            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

@stop
@section('content')

    <div class="card card-outline card-success">
        <div class="card-header">
            <h3 class="card-title font-weight-bold">Gestión de Ofertas</h3>

            <div class="card-tools">
                <div class="btn-group">
                    <a  href="{{ route('programas.create') }}" class="btn btn-success open-modal" >
                        <i class="fas fa-plus"></i> Crear Ofertas
                    </a>
                    <a href="{{ route('areas.create') }}" class="btn btn-info  open-modal">
                        <i class="fas fa fa-plus-square"></i> Crear Areas
                    </a>
                </div>

                
            </div>
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table table-hover text-nowrap">
                <thead>
                    <tr>
                        <th style="width: 10px">Codigo</th>
                        <th>Nombre</th>
                        <th>Area</th>
                        <th style="width: 200px">Fecha creación</th>
                        <th style="width: 100px">Opc</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($programas as $programa)
                    <tr id="row_{{$programa->id}}">
                        <td> {{ $programa->codigo }} </td>
                        <td> {{ $programa->nombre }} </td>
                        <td class="font-weight-bold"> {{$programa->area}} </td>
                        <td> {{  date('d-M-Y',strtotime($programa->created_at)) }} </td>
                        <td>
                            <a class="open-modal bg-info btn-sm" href="{{route('programas.edit',['programa' => $programa->id])}}" >
                                <i class="fas fa-pencil-alt"></i>
                            </a>

                            <a class="bg-danger btn-sm ml-1" href="javascript:eliminar_registro('{{$programa->id}}')">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    </tr>
                    @endforeach

                    @if ($programas->count()==0)
                        <tr>
                            <td colspan="5" class="text-center"> No hay programas registrados</td>
                        </tr>
                    @endif

                </tbody>
            </table>
        </div>
        {{ $programas->render() }}

        <!-- /.card-body -->
    </div>

    <div id="modal-add"></div>

@stop
@section('js')
<script src="/plugins/sweetalert/sweetalert2.min.js"></script>
    <script>

        function eliminar_registro(id){
    
            data = {
                "id": id,
                "_token": "{{ csrf_token() }}",
            },
            swal({
            title: '',
            text: "Esto podria afectar los cursos abiertos, esta seguro de eliminar la oferta seleccionada y cursos abiertos?",
            type: "warning",
            showCancelButton: true,
            closeOnConfirm: false,
            showLoaderOnConfirm: true
            }).then(function(result) {
                if(result.value){
                    $.ajax(
                    {
                        url:"programas/"+id,
                        type: 'DELETE',
                        data:data,
                        success :function(reponse){
                            if(reponse.success){
                                toastr.success('Oferta eliminada exitosamente');
                                $("#row_"+id).remove();
    
                            }else{
                                toastr.error('No fue posible eliminar la oferta');
                            }
                        },
                        error: function (response) {
                            toastr.error('Error al procesar la solicitud')
                        }
                    });
                }
    
            });
        }
        
    </script>

@stop

resources/views/programas/modal-registro.blade.php
<div class="modal fade" id="modal-lg" aria-hidden="true" data-backdrop="static">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header bg-success">
          <h4 class="modal-title">Gestión de Ofertas</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <form id="formProgramas"  class="save-ajax" method="{{$object->exists? 'POST':'POST'}}" data-has-files='true' action="{{ $object->exists? route('programas.update', ['programa' => $object->id]):route('programas.store') }}">
            @csrf
            @if($object->exists)
                <input type="hidden" value="{{$object->exists ? $object->id: '0'}}"  id="id" name="id">
                <input hidden name="_method" value="PUT">
            @endif
            <div class="modal-body">
                
                <div class="card-body row">
                    <div class="col-sm-6">
                        <div class="form-group">
                            <label for="codigo">Codigo del programa: <span class="text-danger">*</span></label>
                            <input type="text" class="form-control" id="codigo" name="codigo" placeholder="Ingrese codigo del programa"  value="{{ $object->codigo }}">
                            <div data-feedback="codigo" class="text-danger">                           
                            </div>

                        </div>
                    </div>

                    <div class="col-sm-6">
                        <div class="form-group">
                            <label>Area: <span class="text-danger">*</span> </label>
                            <select name="area_id" class="form-control">
                            @foreach ($areas as $area)

                            @if ($area->id == $object->area_id)

                                <option value="{{$area->id}}" selected>{{$area->nombre}}</option>
                            @else
                                <option value="{{$area->id}}">{{$area->nombre}}</option>
                            @endif

                            @endforeach
                            </select>
                            <div data-feedback="area_id" class="text-danger">                           
                            </div>

                        </div>
                    </div>
                    
                    <div class="col-sm-12">
                        <div class="form-group">
                            <label for="nombre">Nombre del Programa: <span class="text-danger">*</span> </label>
                            <input type="text" class="form-control text-capitalize" name="nombre" id="nombre" placeholder="Ingrese nombre del programa" value="{{ $object->nombre }}">
                            <div data-feedback="nombre" class="text-danger">                           
                            </div>

                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="form-group">
                            <label>Descripción: <span class="text-danger">*</span> </label>
                            <textarea class="form-control" rows="7" name="descripcion" placeholder="Ingrese descripción del programa"> {{$object->descripcion}} </textarea>
                            <div data-feedback="descripcion" class="text-danger">                           
                            </div>

                        </div>
                    </div>

                </div>
                    <!-- /.card-body -->

            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Guardar</button>
            </div>
        </form>

      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>